// src/components/TwWatchedCard.tsx
// Third Party
import { EllipsisVerticalIcon, TrashIcon } from '@heroicons/react/24/outline';
// Local
import { Card } from '@/components/ui/card';
import TwCircleButton from './base/TwCircleButton';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { Button } from './ui/button';

type onType = {
  season: number;
  episode: number;
  name: string;
};

type Props = {
  image: string;
  name: string;
  on: onType;
  percentage: number;
  status: 'Running' | 'Ended';
  onDelete: () => void;
  onRewatch: () => void;
  onContinue: () => void;
  deleteable?: boolean;
};

const formatOn = (on: onType) => {
  const { season, episode } = on;
  const s = season < 10 ? `0${season}` : season;
  const e = episode < 10 ? `0${episode}` : episode;

  return `Season ${s} Episode ${e}`;
};

const TwWatchedCard = (props: Props) => {
  const renderStatus = () => {
    if (props.status != 'Ended') {
      return (
        <div className="flex items-center justify-center h-3 w-3 relative">
          <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-green-200 opacity-75"></span>
          <span className="relative inline-flex rounded-full h-3 w-3 bg-green-500 border-2 border-neutral-900"></span>
        </div>
      );
    }

    return (
      <div className="flex items-center justify-center h-3 w-3 relative">
        <span className="relative inline-flex rounded-full h-3 w-3 bg-red-500 border-2 border-neutral-900"></span>
      </div>
    );
  };

  return (
    <Card className="w-full max-w-sm min-h-[160px] pt-2 pb-2 pr-3 pl-[134px] relative overflow-hidden">

      <div className="absolute top-2 right-2 z-50 inline-block text-left">
        <DropdownMenu>
          <DropdownMenuTrigger>
            <span className="sr-only">Open options</span>
            <EllipsisVerticalIcon className="h-5 w-5" aria-hidden="true" />
          </DropdownMenuTrigger>
          <DropdownMenuContent>
            <Button variant="destructive" className="w-full" onClick={(e) => { e.preventDefault(); props.onDelete() }}>
              <TrashIcon className="mr-3 h-5 w-5" aria-hidden="true" /> Delete
            </Button>
          </DropdownMenuContent>
        </DropdownMenu>
      </div>

      <img className="absolute top-0 left-0 h-full z-0 rounded-2xl" src={props.image} alt={`${props.name} poster`} />

      <div className="absolute left-2 top-2">
        {renderStatus()}
      </div>

      <h5 className="w-full text-sm text-white tracking-wide font-semibold mt-1 text-nowrap text-ellipsis pr-4 overflow-hidden"
        title={props.name}>{props.name}</h5>

      <p className="text-sm text-gray-400 mb-1">{formatOn(props.on)}</p>
      <p className="text-xs text-gray-400 mb-2 text-nowrap text-ellipsis pr-4 overflow-hidden"
        title={props.on.name}>{props.on.name}</p>

      <div className="h-[8px] w-full rounded-full relative overflow-hidden mr-2 border-[2px] border-zinc-800">
        <div className="absolute top-0 left-0 h-full rounded-full bg-indigo-600" style={{ width: `${props.percentage}%` }} />
      </div>

      {props.percentage == 100 ? (
        <TwCircleButton
          className="absolute bottom-3 right-[55px] transform-gpu"
          type="refresh"
          size="xs"
          onClick={props.onRewatch}
        />
      ) : null}
      <TwCircleButton
        className="absolute bottom-3 right-2 transform-gpu"
        type="play"
        size="xs"
        onClick={props.onContinue}
      />
    </Card>
  );
};

export default TwWatchedCard;

// src/components/TwWatchedCard.vue
<script>
import TwCard from '@/components/base/TwCard';
import TwCircleButton from '@/components/base/TwCircleButton.vue';

export default {
  name: 'TwWatchedCard',
  props: {
    image: String,
    name: String,
    episodeTitle: String,
    on: String,
    id: String,
    deleteable: Boolean
  },
  components: {
    TwCard,
    TwCircleButton
  }
};
</script>

<template>
  <tw-card class="group w-full max-w-sm min-h-[160px] pt-2 pb-2 pr-3 pl-[134px] relative overflow-hidden">
    <tw-circle-button type="trash" size="xs"
      class="absolute top-2 left-2 z-50 -translate-x-[130%] group-hover:translate-x-0 ease-out duration-300"
      @click="$emit('onDelete')"></tw-circle-button>

    <img class="absolute top-0 left-0 h-full z-0" :src="image" :alt="`${name} poster`" />

    <div class="flex flex-row items-center">
      <div class="h-1 w-full rounded-full bg-gray-200 relative overflow-hidden mr-2">
        <div class="absolute top-0 left-0 h-full rounded-full bg-indigo-600" :style="{ width: `50%` }" />
      </div>

      <div>
        <span class="flex items-center justify-center h-3 w-3 relative">
          <span class="animate-ping absolute inline-flex h-full w-full rounded-full bg-green-200 opacity-75"></span>
          <span class="relative inline-flex rounded-full h-2 w-2 bg-green-500"></span>
        </span>
      </div>
    </div>

    <h5 class="text-lg tracking-wide font-semibold mt-2">{{ name }}</h5>
    <p class="text-sm text-gray-500 mb-2">{{ episodeTitle }}</p>
    <p class="text-xs text-gray-500">{{ on }}</p>

    <TwCircleButton class="absolute bottom-3 right-12 transform-gpu" type="refresh" size="xs"
      @click="$emit('onRewatch')">
    </TwCircleButton>
    <TwCircleButton class="absolute bottom-3 right-2 transform-gpu" type="play" size="xs" @click="$emit('onContinue')">
    </TwCircleButton>
  </tw-card>
</template>
