// src/components/search/TwSearchResultItem.vue
<script>
import TwCard from '@/components/base/TwCard.vue';
import TwCircleButton from '@/components/base/TwCircleButton';
import TwBadge from '@/components/base/TwBadge.vue';

export default {
   name: 'TwSearchResultItem',
   props: {
      name: String,
      image: String,
      released: String,
      genres: Array,
      summary: String,
      disabled: Boolean
   },
   methods: {
      extractYear(date) {
         if(!date) return '-';
         const dateObj = new Date(date);
         return dateObj.getFullYear();
      }
   },
   components: {
      TwCard,
      TwCircleButton,
      TwBadge
   }
};
</script>

<template>
   <div class="flex gap-2 justify-between p-5 border-b-2 border-zinc-800">
      <div class="flex gap-5 text-sm">
         <div>
            <img class="min-w-[100px] max-w-[100px] h-auto rounded-lg border-2 border-zinc-800" :src="image"/>
         </div>
         
         <div>
            <div class="flex flex-row flex-1 justify-between">
               <p class="text-slate-200 font-bold mb-2">{{ name }} 
                  <span class="text-slate-500 text-xs">{{ extractYear(released) }}</span>
               </p>
               <tw-circle-button type="plus" size="xs" @click="$emit('onAdd')" />
            </div>

            <tw-badge v-for="item in genres" class="mr-2">{{ item }}</tw-badge>
            
            <p class="text-slate-400 text-xs mt-4" v-html="summary"></p>
         </div>
      </div>
   </div>
</template>

// src/components/search/TwSearchResultItem.tsx
// Local
import TwCircleButton from "@/components/base/TwCircleButton";
import TwBadge from "@/components/base/TwBadge";

type Props = {
   name: string;
   image: string;
   released?: string;
   genres?: string[];
   summary: string;
   disabled?: boolean;
   onAdd?: () => void;
};

const TwSearchResultItem = (props: Props) => {
   const extractYear = (date: string): string => {
      if (!date) return "-";
      const dateObj = new Date(date);

      return `${dateObj.getFullYear()}`;
   };

   return (
      <div className=" p-5 border-b-2 border-zinc-800">
         <div className="flex gap-5 text-sm">
            <div>
               <img className="min-w-[100px] max-w-[100px] h-auto rounded-lg border-2 border-zinc-800" src={props.image} />
            </div>

            <div>
               <div className="flex flex-row flex-1 justify-between">
                  <p className="text-slate-200 font-bold mb-2">{props.name}
                     <span className="text-slate-500 text-xs"> {extractYear(props.released || '')}</span>
                  </p>
                  {props.onAdd ? <TwCircleButton type="plus" size="xs" onClick={props.onAdd} /> : null}
               </div>

               {props.genres?.map((item) => (
                  <TwBadge className="mr-2" key={item}>{item}</TwBadge>
               ))}

               <div className="relative mb-4">
                  <div className="text-slate-400 text-xs mt-5 pb-6 h-[80px] overflow-y-scroll" dangerouslySetInnerHTML={{ __html: props?.summary }}></div>
                  <div className="absolute bottom-0 left-0 w-full h-6 bg-gradient-to-t from-neutral-900 pointer-events-none"></div>
               </div>
            </div>
         </div>
      </div>
   );
};

export default TwSearchResultItem;
